Added Google Recaptcha in contact page
first-brick/landing-website pull request #21
Opened 2020-10-10 22:12 UTC by saikumar221

2020-10-11 01:37 UTC, pradipta commented
Do you need this key to start working on it and testing it? Is it a blocked from our side?
If yes, I'll send you the key today in some time.

2020-10-11 08:20 UTC, saikumar221 commented
I have tested it on my end with a security key I generated, it works perfectly. 
To test it from your end generate the key, put it in the placeholder as mentioned above.
The placement, size of the component can be tested by deploying it on the localhost. Free Google reCaptcha's functionality doesn't work on localhost, it must be deployed on to the website with a domain name. It needs a valid domain with a valid host and must not include any protocol, path, port, query, or fragment.

2020-10-11 09:12 UTC, first-brick commented
@pradipta @saikumar221 Do I need it with Recaptcha v1 or v2? Or does it not matter?

2020-10-11 09:27 UTC, pradipta commented
@first-brick the keys have been generated, don't worry about that. I will paste it in.
@saikumar221 the div placement and all looks good. Not a problem. But I do not see a validation code. I guess I can still send the query without the captcha verification.
That was what I meant with my first question? Do you want me to merge it with the keys so that you can start working on the validation?

2020-10-11 11:24 UTC, saikumar221 commented
@pradipta  I generated a key and placed it here, This will now work locally on localhost too.
Also Added the validation logic, please check the latest commit.

2020-10-12 05:31 UTC, pradipta commented on views/index.ejs
> +                  document.getElementById('captchamsg').innerHTML="Please Verify the Captcha";
Change this line to `alert("Please Verify the Captcha");`

2020-10-12 05:32 UTC, pradipta requested changes

2020-10-12 05:32 UTC, pradipta commented on views/index.ejs
> +                  document.getElementById('captchamsg').innerHTML="Please Verify the Captcha";
Rest, LGTM

2020-10-12 06:31 UTC, saikumar221 commented
@pradipta requested changes have been made.

2020-10-12 06:33 UTC, saikumar221 commented
@pradipta requested changes are updated.

2020-10-12 06:42 UTC, pradipta approved these changes

2020-10-12 06:47 UTC, first-brick approved these changes

2020-10-12 06:47 UTC, merged